// Code generated by goctl. DO NOT EDIT.
package types

type GetOneReq struct {
	UseUrl string `josn:"use-url,optional"` // 申请使用这个代理的是那个 Url，返回的代理优先级也跟这个 Url 正相关
	Stable bool   `json:"stable,optional"`  // 是否使用稳定的代理，比如自建的代理
}

type GetOneResp struct {
	ID uint64 `json:"id"` // 本系统内的唯一 ID
	IP string `json:"ip"` // 随机的 IP
}
