// Code generated by goctl. DO NOT EDIT!
// Source: onlineVideoDl.proto

package server

import (
	"context"

	"github.com/allanpk716/Downloadhub/service/onlineVideoDl/cmd/rpc/internal/logic"
	"github.com/allanpk716/Downloadhub/service/onlineVideoDl/cmd/rpc/internal/svc"
	"github.com/allanpk716/Downloadhub/service/onlineVideoDl/cmd/rpc/onlineVideoDl"
)

type OnlineVideoDlServer struct {
	svcCtx *svc.ServiceContext
}

func NewOnlineVideoDlServer(svcCtx *svc.ServiceContext) *OnlineVideoDlServer {
	return &OnlineVideoDlServer{
		svcCtx: svcCtx,
	}
}

func (s *OnlineVideoDlServer) GetProcessingTasks(ctx context.Context, in *onlineVideoDl.TasksInProgressRequest) (*onlineVideoDl.TasksInProgressResponse, error) {
	l := logic.NewGetProcessingTasksLogic(ctx, s.svcCtx)
	return l.GetProcessingTasks(in)
}
