// Code generated by goctl. DO NOT EDIT!
// Source: proxyhub.proto

//go:generate mockgen -destination ./getter_mock.go -package getter -source $GOFILE

package getter

import (
	"context"
	ProxyHub2 "github.com/allanpk716/Downloadhub/service/proxyhub/rpc/ProxyHub"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	GetOneReq  = ProxyHub2.GetOneReq
	GetOneResp = ProxyHub2.GetOneResp

	Getter interface {
		//  获取一个随机代理
		Get(ctx context.Context, in *GetOneReq) (*GetOneResp, error)
	}

	defaultGetter struct {
		cli zrpc.Client
	}
)

func NewGetter(cli zrpc.Client) Getter {
	return &defaultGetter{
		cli: cli,
	}
}

//  获取一个随机代理
func (m *defaultGetter) Get(ctx context.Context, in *GetOneReq) (*GetOneResp, error) {
	client := ProxyHub2.NewGetterClient(m.cli.Conn())
	return client.Get(ctx, in)
}
