// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxyhub.proto

package ProxyHub

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOneReq struct {
	UseUrl               string   `protobuf:"bytes,1,opt,name=UseUrl,proto3" json:"UseUrl,omitempty"`
	Stable               bool     `protobuf:"varint,2,opt,name=Stable,proto3" json:"Stable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_04943da0064bae8a, []int{0}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetUseUrl() string {
	if m != nil {
		return m.UseUrl
	}
	return ""
}

func (m *GetOneReq) GetStable() bool {
	if m != nil {
		return m.Stable
	}
	return false
}

// -------------------------------------------------------
// 获取若干个代理
type GetOneResp struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneResp) Reset()         { *m = GetOneResp{} }
func (m *GetOneResp) String() string { return proto.CompactTextString(m) }
func (*GetOneResp) ProtoMessage()    {}
func (*GetOneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_04943da0064bae8a, []int{1}
}

func (m *GetOneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResp.Unmarshal(m, b)
}
func (m *GetOneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResp.Marshal(b, m, deterministic)
}
func (m *GetOneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResp.Merge(m, src)
}
func (m *GetOneResp) XXX_Size() int {
	return xxx_messageInfo_GetOneResp.Size(m)
}
func (m *GetOneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResp proto.InternalMessageInfo

func (m *GetOneResp) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetOneResp) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOneReq)(nil), "ProxyHub.getOneReq")
	proto.RegisterType((*GetOneResp)(nil), "ProxyHub.getOneResp")
}

func init() { proto.RegisterFile("proxyhub.proto", fileDescriptor_04943da0064bae8a) }

var fileDescriptor_04943da0064bae8a = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0xaf,
	0xa8, 0xcc, 0x28, 0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x08, 0x00, 0xf1, 0x3d,
	0x4a, 0x93, 0x94, 0xac, 0xb9, 0x38, 0xd3, 0x53, 0x4b, 0xfc, 0xf3, 0x52, 0x83, 0x52, 0x0b, 0x85,
	0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53, 0x43, 0x8b, 0x72, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xa0, 0x3c, 0x90, 0x78, 0x70, 0x49, 0x62, 0x52, 0x4e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47,
	0x10, 0x94, 0xa7, 0xa4, 0xc3, 0xc5, 0x05, 0xd3, 0x5c, 0x5c, 0x20, 0xc4, 0xc7, 0xc5, 0xe4, 0xe9,
	0x02, 0xd6, 0xc9, 0x12, 0xc4, 0xe4, 0xe9, 0x02, 0xe6, 0x07, 0x80, 0x75, 0x70, 0x06, 0x31, 0x79,
	0x06, 0x18, 0x59, 0x71, 0xb1, 0xa5, 0xa7, 0x96, 0x94, 0xa4, 0x16, 0x09, 0x19, 0x70, 0x31, 0xa7,
	0xa7, 0x96, 0x08, 0x09, 0xeb, 0xc1, 0x9c, 0xa1, 0x07, 0x77, 0x83, 0x94, 0x08, 0xa6, 0x60, 0x71,
	0x41, 0x12, 0x1b, 0xd8, 0xdd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x14, 0xf2, 0x1f,
	0xc9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetterClient is the client API for Getter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetterClient interface {
	// 获取一个随机代理
	Get(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error)
}

type getterClient struct {
	cc *grpc.ClientConn
}

func NewGetterClient(cc *grpc.ClientConn) GetterClient {
	return &getterClient{cc}
}

func (c *getterClient) Get(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error) {
	out := new(GetOneResp)
	err := c.cc.Invoke(ctx, "/ProxyHub.getter/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetterServer is the server API for Getter service.
type GetterServer interface {
	// 获取一个随机代理
	Get(context.Context, *GetOneReq) (*GetOneResp, error)
}

// UnimplementedGetterServer can be embedded to have forward compatible implementations.
type UnimplementedGetterServer struct {
}

func (*UnimplementedGetterServer) Get(ctx context.Context, req *GetOneReq) (*GetOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterGetterServer(s *grpc.Server, srv GetterServer) {
	s.RegisterService(&_Getter_serviceDesc, srv)
}

func _Getter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProxyHub.getter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetterServer).Get(ctx, req.(*GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Getter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ProxyHub.getter",
	HandlerType: (*GetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _Getter_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxyhub.proto",
}
