// Code generated by goctl. DO NOT EDIT!
// Source: onlineVideoDl.proto

//go:generate mockgen -destination ./onlinevideodl_mock.go -package onlinevideodlclient -source $GOFILE

package onlinevideodlclient

import (
	"context"

	"github.com/allanpk716/Downloadhub/service/onlineVideoDl/cmd/rpc/onlineVideoDl"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	TasksInProgressRequest  = onlineVideoDl.TasksInProgressRequest
	TasksInProgressResponse = onlineVideoDl.TasksInProgressResponse
	OnlineVideoTask         = onlineVideoDl.OnlineVideoTask

	OnlineVideoDl interface {
		GetProcessingTasks(ctx context.Context, in *TasksInProgressRequest) (*TasksInProgressResponse, error)
	}

	defaultOnlineVideoDl struct {
		cli zrpc.Client
	}
)

func NewOnlineVideoDl(cli zrpc.Client) OnlineVideoDl {
	return &defaultOnlineVideoDl{
		cli: cli,
	}
}

func (m *defaultOnlineVideoDl) GetProcessingTasks(ctx context.Context, in *TasksInProgressRequest) (*TasksInProgressResponse, error) {
	client := onlineVideoDl.NewOnlineVideoDlClient(m.cli.Conn())
	return client.GetProcessingTasks(ctx, in)
}
